component_depth: 7
languages:
- name: scala
  production:
    include:
      - .*/Library/src/main/.*\.scala
      - .*/ProjectExample/src/main/.*\.scala
  test:
    include:
      - .*/Library/src/test/.*\.scala
      - .*/ProjectExample/src/test/.*\.scala
