name: CI
on:
  push:
    paths-ignore:
      - ".gitignore"
      - ".bettercodehub.yml"
      - ".scalafix.conf"
      - ".scalafmt.conf"
      - "LICENSE"
      - "README.md"
      - "PULL_REQUEST_TEMPLATE.md"
      - "scalastyle-config.xml"
      - "stryker4s.conf"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - ".bettercodehub.yml"
      - ".scalafix.conf"
      - ".scalafmt.conf"
      - "LICENSE"
      - "README.md"
      - "PULL_REQUEST_TEMPLATE.md"
      - "scalastyle-config.xml"
      - "stryker4s.conf"

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: clean
        run: make deep_clean

      - name: build
        run: |
          ./scripts/spark-cross-compile.sh
      - name: test
        run: |
          ./scripts/spark-cross-fmt.sh
          ./scripts/spark-cross-test.sh

      - name: unit-test-coverage
        run: make test_coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: clean-up
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
