name: Release
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PGP_SECRET: ${{ secrets.PGP_SECRET }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: release-staging
        run: |
          ./scripts/spark-cross-publish.sh library true
          ./scripts/spark-cross-publish.sh testHelper true
          ./scripts/spark-cross-publish.sh libraryConfigsScallop true
        if: startsWith(github.ref, 'refs/tags/') != true

      - name: release-production
        run: |
          ./scripts/spark-cross-publish.sh library
          ./scripts/spark-cross-publish.sh testHelper
          ./scripts/spark-cross-publish.sh libraryConfigsScallop
        if: startsWith(github.ref, 'refs/tags/v')

      - name: clean-up
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt
